### PR TITLE
D8 nid 280

### PR DESCRIPTION
**Pull request by DuttonMa**
Added Nightwatch tests for user dashboard

### CODE REVIEW

**Comment by johangant** [comment]
Good to see the passwords aren't baked into the code. In future, I wonder if it'd make sense to keep the usernames + passwords in env vars and eliminate the temptation for someone to brute-force auth if they spotted those usernames in the source code?

**Comment by omahm** [comment]
> Good to see the passwords aren't baked into the code. In future, I wonder if it'd make sense to keep the usernames + passwords in env vars and eliminate the temptation for someone to brute-force auth if they spotted those usernames in the source code?

Yeah, I like this idea... ..the less they know.

**Comment by DuttonMa** [comment]
> Looks good. One consideration might be to check that on the node/add screen certain users don't have access to certain types, verify that 'Create Publication' for example doesn't exist for health condition authors if they don't have that permission.

Good idea, thanks, have done that now

**Comment by DuttonMa** [comment]
> Good to see the passwords aren't baked into the code. In future, I wonder if it'd make sense to keep the usernames + passwords in env vars and eliminate the temptation for someone to brute-force auth if they spotted those usernames in the source code?

Good point, thanks, have now put a prefix in the environment vars so that the full user name is not visible

**Pull request merged**
